name: Flex
markdown: redcarpet
pygments: true

links:
  github: https://github.com/ddavison
  twitter: http://twitter.com/sircapsalot
  stackoverflow: http://stackoverflow.com/users/1695163/sircapsalot
